name: ci-golang
on:
  pull_request:
    branches:
      - dev

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix }}
      - run: go test
      - run: go run math.go
    strategy:
      matrix:
        go: ["1.14", "1.15"]
